# This is an example config file

[server]
hostname = "192.168.1.1"
port = "8080"
TLS = true

[settings]
threads = 1
throttle = 50
seed = 3223372036854775808

[session]
length = 50
# select weights to IMAP commands:
# [create, delete, append, store, expunge]
distribution = [1.0, 1.0, 5.0, 5.0, 5.0]
