# This is an example config file

[server]
hostname = "localhost"
port = "993"
TLS = true #unused

[settings]
threads = 1
sessions = 3
throttle = 50 #unused
seed = 3223372036854775808

[session]
minlength = 15
maxlength = 40
