
# This is an example config file

[server]
addr = "localhost:11111"
TLS = true # unused

[settings]
threads = 1
sessions = 80
throttle = 50 # unused
seed = 3223372035854775808

[session]
minlength = 15
maxlength = 40
